    SET PAGESIZE 0 EMBEDDED ON
    SET LINESIZE 1000
    SET VERIFY OFF
    SET ECHO OFF
    SET HEADING ON
    SET SERVEROUTPUT OFF;
    SET PAGES     0
    SET DEFINE ON;
    
    SPOOL '&1'
    
    COLUMN COD_PARAMETRO FORMAT a100 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a100 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a100 HEADING DES_VALOR;
    
    SELECT  TDFE_PARAMETRO_APLICACAO.COD_PARAMETRO AS COD_PARAMETRO, TDFE_PARAMETRO.DES_PARAMETRO AS DES_PARAMETRO, TDFE_PARAMETRO_APLICACAO.DES_VALOR AS DES_VALOR FROM TDFE_PARAMETRO_APLICACAO INNER JOIN TDFE_PARAMETRO ON(TDFE_PARAMETRO_APLICACAO.COD_PARAMETRO=TDFE_PARAMETRO.COD_PARAMETRO);

    SPOOL OFF
    SPOOL '&2'

    COLUMN COD_EMPRESA FORMAT 999999999 HEADING COD_EMPRESA;
    COLUMN COD_PARAMETRO FORMAT a60 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a100 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a60 HEADING DES_VALOR;

    SELECT TFRW_EMPRESA.COD_EMPRESA AS COD_EMPRESA, TDFE_PARAMETRO_EMPRESA.COD_PARAMETRO  AS COD_PARAMETRO, TDFE_PARAMETRO.DES_PARAMETRO AS DES_PARAMETRO, TDFE_PARAMETRO_EMPRESA.DES_VALOR AS DES_VALOR FROM TDFE_PARAMETRO_EMPRESA INNER JOIN TFRW_EMPRESA ON(TDFE_PARAMETRO_EMPRESA.COD_EMPRESA=TFRW_EMPRESA.COD_EMPRESA) INNER JOIN TDFE_PARAMETRO ON(TDFE_PARAMETRO_EMPRESA.COD_PARAMETRO=TDFE_PARAMETRO.COD_PARAMETRO);

    SPOOL OFF
    SPOOL '&3'
    
    COLUMN COD_EMPRESA FORMAT 99999 HEADING COD_EMPRESA;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    COLUMN DES_NIVEL FORMAT a60 HEADING DES_NIVEL;
    COLUMN COD_PARAMETRO FORMAT a60 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a60 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a200 HEADING DES_VALOR;
    
    SELECT TDFE_PARAMETRO_ESTABELECIMENTO.COD_EMPRESA AS COD_EMPRESA, TDFE_PARAMETRO_ESTABELECIMENTO.COD_ESTABELECIMENTO AS COD_ESTABELECIMENTO, TDFE_PARAMETRO_NIVEL.DES_NIVEL AS DES_NIVEL,TDFE_PARAMETRO_ESTABELECIMENTO.COD_PARAMETRO AS COD_PARAMETRO, TDFE_PARAMETRO.DES_PARAMETRO AS DES_PARAMETRO, 	TDFE_PARAMETRO_ESTABELECIMENTO.DES_VALOR AS DES_VALOR FROM TDFE_PARAMETRO_ESTABELECIMENTO INNER JOIN TDFE_PARAMETRO ON(TDFE_PARAMETRO_ESTABELECIMENTO.COD_PARAMETRO=TDFE_PARAMETRO.COD_PARAMETRO) LEFT JOIN TDFE_PARAMETRO_NIVEL ON (TDFE_PARAMETRO_NIVEL.DES_TABLE='TDFE_PARAMETRO_ESTABELECIMENTO' AND TDFE_PARAMETRO.COD_NIVEL=TDFE_PARAMETRO_NIVEL.COD_NIVEL);
    
    SPOOL OFF
    SPOOL '&4'
    
    COLUMN CONNECTION_STRING FORMAT a400 HEADING CONNECTION_STRING;
    COLUMN ID_ODBC_CONNECTION_STRING FORMAT 99999 HEADING ID_ODBC_CONNECTION_STRING;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    COLUMN COD_EMPRESA FORMAT 99999 HEADING COD_EMPRESA;
    
    SELECT DISTINCT(TDFE_ODBC_CONNECTION_STRING.CONNECTION_STRING) AS CONNECTION_STRING,TDFE_ODBC_CONNECTION_STRING.ID_ODBC_CONNECTION_STRING AS ID_CONNECTION, TDFE_ODBC_ESTABELECIMENTO.COD_ESTABELECIMENTO AS COD_ESTAB, TDFE_ODBC_ESTABELECIMENTO.COD_EMPRESA AS COD_EMPRESA FROM TDFE_ODBC_CONNECTION_STRING INNER JOIN TDFE_ODBC_ESTABELECIMENTO ON(TDFE_ODBC_CONNECTION_STRING.ID_ODBC_CONNECTION_STRING=TDFE_ODBC_ESTABELECIMENTO.ID_ODBC_CONNECTION_STRING) ORDER BY COD_EMPRESA, COD_ESTAB;
    
    SPOOL OFF
    SPOOL '&5'
    
    COLUMN COD_EMPRESA FORMAT 99999 HEADING COD_EMPRESA;
    COLUMN COD_ODBC FORMAT a60 HEADING COD_ODBC;
    COLUMN QUERY FORMAT a4050 HEADING QUERY;
    COLUMN ID_ODBC_CONNECTION_STRING FORMAT 99999 HEADING ID_ODBC_CONNECTION_STRING;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    
    SELECT TDFE_ODBC.COD_EMPRESA AS COD_EMPRESA, TDFE_ODBC.COD_ODBC AS COD_ODBC, TDFE_ODBC.QUERY AS QUERY FROM TDFE_ODBC
    
    SPOOL OFF
    SPOOL '&6'
    
    COLUMN COD_PARAMETRO FORMAT a100 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a100 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a200 HEADING DES_VALOR;
    COLUMN ID_ODBC_CONNECTION_STRING FORMAT 99999 HEADING ID_ODBC_CONNECTION_STRING;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    
    SELECT TAUD_PARAMETRO_APLICACAO.COD_PARAMETRO AS COD_PARAMETRO, TAUD_PARAMETRO.DES_PARAMETRO AS DES_PARAMETRO, TAUD_PARAMETRO_APLICACAO.DES_VALOR AS DES_VALOR FROM TAUD_PARAMETRO_APLICACAO INNER JOIN TAUD_PARAMETRO ON(TAUD_PARAMETRO_APLICACAO.COD_PARAMETRO=TAUD_PARAMETRO.COD_PARAMETRO)
    
    SPOOL OFF
    SPOOL '&7'
    
    COLUMN COD_EMPRESA FORMAT 99999 HEADING COD_EMPRESA;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    COLUMN COD_PARAMETRO FORMAT a60 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a100 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a60 HEADING DES_VALOR;
    
    SELECT TAUD_PARAMETRO_ESTABELECIMENTO.COD_EMPRESA AS COD_EMPRESA, TAUD_PARAMETRO_ESTABELECIMENTO.COD_ESTABELECIMENTO AS COD_ESTABELECIMENTO,  TAUD_PARAMETRO_ESTABELECIMENTO.COD_PARAMETRO AS COD_PARAMETRO, TAUD_PARAMETRO.DES_PARAMETRO AS DES_PARAMETRO, TAUD_PARAMETRO_ESTABELECIMENTO.DES_VALOR AS DES_VALOR FROM TAUD_PARAMETRO_ESTABELECIMENTO INNER JOIN TAUD_PARAMETRO ON(TAUD_PARAMETRO_ESTABELECIMENTO.COD_PARAMETRO=TAUD_PARAMETRO.COD_PARAMETRO) ORDER BY TAUD_PARAMETRO_ESTABELECIMENTO.COD_PARAMETRO, TAUD_PARAMETRO_ESTABELECIMENTO.COD_ESTABELECIMENTO;
    
    SPOOL OFF
    SPOOL '&8'
    
    COLUMN COD_EMPRESA FORMAT 99999 HEADING COD_EMPRESA;
    COLUMN COD_ESTABELECIMENTO FORMAT 99999 HEADING COD_ESTABELECIMENTO;
    COLUMN COD_PARAMETRO FORMAT a60 HEADING COD_PARAMETRO;
    COLUMN DES_PARAMETRO FORMAT a100 HEADING DES_PARAMETRO;
    COLUMN DES_VALOR FORMAT a60 HEADING DES_VALOR;
    
    BEGIN  SELECT CAST(TDFE_GRUPO_DISTRIBUICAO.DESCRICAO AS VARCHAR(40)) AS DES_GRUPO_DIST,CAST(TDFE_GRUPO_DIST_EMAIL.EMAIL AS VARCHAR(100)) AS EMAIL_GRUPO_DIST FROM TDFE_GRUPO_DIST_EMAIL INNER JOIN TDFE_GRUPO_DISTRIBUICAO ON(TDFE_GRUPO_DISTRIBUICAO.ID=TDFE_GRUPO_DIST_EMAIL.ID_GRUPO_DISTRIBUICAO) ORDER BY DES_GRUPO_DIST,EMAIL_GRUPO_DIST;SELECT CAST(TDFE_GRUPO_DISTRIBUICAO.DESCRICAO AS VARCHAR(40)) AS DES_GRUPO_DIST,CAST(TDFE_GRUPO_DIST_USUARIO.COD_LOGIN AS VARCHAR(100)) AS LOGIN_DIST_USUAR FROM TDFE_GRUPO_DIST_USUARIO INNER JOIN TDFE_GRUPO_DISTRIBUICAO ON(TDFE_GRUPO_DISTRIBUICAO.ID=TDFE_GRUPO_DIST_USUARIO.ID_GRUPO_DISTRIBUICAO) ORDER BY DES_GRUPO_DIST, LOGIN_DIST_USUAR; SELECT CAST(TDFE_GRUPO_DISTRIBUICAO.DESCRICAO AS VARCHAR(40)) AS DES_GRUPO_DIST,CAST(TDFE_GRUPO_DISTRIBUICAO.FLG_ATIVO AS VARCHAR(3)) AS FLG_ATIVO,CAST(TDFE_GRUPO_DIST_MENSAGEM.ID_MENSAGEM AS VARCHAR(5)) AS COD_TIPO_MENSG,CAST(TDFE_MENSAGENS_EMAIL.TIPO_MENSAGEM AS VARCHAR(3)) AS COD_TIPO_MENSG,CAST(TDFE_MENSAGENS_EMAIL.TITULO_MENSAGEM AS VARCHAR(100)) AS TIT_MENSG_EMAIL,CAST(TDFE_MENSAGENS_EMAIL.MENSAGEM AS VARCHAR(350)) AS DES_MENSG_EMAIL FROM TDFE_GRUPO_DIST_MENSAGEM INNER JOIN TDFE_GRUPO_DISTRIBUICAO ON(TDFE_GRUPO_DIST_MENSAGEM.ID_GRUPO_DISTRIBUICAO=TDFE_GRUPO_DISTRIBUICAO.ID) LEFT JOIN TDFE_MENSAGENS_EMAIL ON(TDFE_MENSAGENS_EMAIL.ID_MENSAGEM=TDFE_GRUPO_DIST_MENSAGEM.ID_MENSAGEM) ORDER BY TDFE_GRUPO_DISTRIBUICAO.DESCRICAO, TDFE_MENSAGENS_EMAIL.TIPO_MENSAGEM, TDFE_GRUPO_DIST_MENSAGEM.ID_MENSAGEM; END;
    
    SPOOL OFF
    